### ISSUE TITLE
ItemClickListener not working

### ISSUE THREAD

**Issue by johnGachihi** [Indiatsi/FleetManagement#1]
I found that the listener wasn't really set on the items.
In this constructor, https://github.com/Indiatsi/FleetManagement/blob/a1bc4187698f78e19d9692177d7f1bca55501092/AndroidStudioProjects/VehicleTracker/app/src/main/java/com/example/myapplication/ListOnlineViewHolder.java#L12-L15
add 
```
itemView.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        itemClickListener.onClick(v, getAdapterPosition());
    }
}
```
I haven't tested it so this code might have some syntax issues.
If this doesn't make it work, tell me.

**Comment by Indiatsi** [comment]
It's worked, thank you.
I had put the onClick method, outside of the constructor ://

Thank you so much.
